### ISSUE TITLE
Icon上的淡蓝透明前景色

### ISSUE THREAD

**Issue by wujian0108** [Zhu-Aemon/music_gallery#1]
Hello,你解决那个icon淡蓝透明前景色的问题了吗？

**Comment by Zhu-Aemon** [comment]
天哪，没想到这么久了还会有人看到我在stackoverflow上提的问题来我的repo给我提issue...
感谢关注，那个问题其实到现在也没有解决，只要你设置QListWidget的icon，他就一定会遇到这个问题
到最后我放弃了淡蓝色的背景改用了纯白色的背景，这样就不会受影响了
话说回来这个项目我已经准备重新用vue+electron开发了，python+pyside确实不是很适合桌面应用的开发

**Comment by wujian0108** [comment]
溜了，就为了做个缩略图，以为可以偷个懒，用了ListWidget的IconMdoe，结果卡了半个月。
